apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.cluster_name }}
  {%- if values.description %}
  description: ${{ values.description }}
  {%- endif %}
  links:
  - url: https://openshift-gitops-server-openshift-gitops.${{ values.cluster_url }}/applications/openshift-gitops/${{ values.cluster_name }}
    title: ArgoCD
    icon: dashboard
  - url: https://console-openshift-console.___rosa_url___/dashboards 
    title: ROSA Console
    icon: dashboard
  annotations:
    argocd/app-name: ${{ values.cluster_name }}
    backstage.io/kubernetes-id: ${{ values.cluster_name }}
    janus-idp.io/tekton-enabled : 'true'
    janus-idp.io/tekton : ${{ values.cluster_name }}
    tektonci/build-namespace: ${{ values.cluster_name }}
    backstage.io/kubernetes-namespace: ${{ values.cluster_name }}
    github.com/project-slug: ${{ values.git_owner_name }}/${{ values.cluster_name }}
spec:
  type: rosa
  system: ${{ values.system | dump }}
  lifecycle: production
  owner: ${{ values.owner | dump }}
  git: ${{ values.git }}
  git_host_url: ${{ values.git_host_url }}
  git_owner_name: ${{ values.git_owner_name }}
