apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-${{ values.cluster_name }}-el 
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: el-${{ values.cluster_name }}-listener
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
