apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-github-webhook-secret
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target: # ExternalSecret から作成されるKubernetes Secretを指定する
    name: github-webhook-secret
  data: # 取得する秘匿情報を指定する
  - secretKey: github_webhook_secret # 作成するSecretのkeyを指定
    remoteRef:
      key: github_webhook_secret # AWS Secrets Managerに登録したシークレット名
      property: github_webhook_secret # シークレットに登録したキーを指定
