apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-rosa-password
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target: # ExternalSecret から作成されるKubernetes Secretを指定する
    name: rosa-password
  data: # 取得する秘匿情報を指定する
  - secretKey: ROSA_USERNAME # 作成するSecretのkeyを指定
    remoteRef:
      key: rosa_username # AWS Secrets Managerに登録したシークレット名
      property: ROSA_USERNAME # シークレットに登録したキーを指定
  - secretKey: ROSA_PASSWORD # 作成するSecretのkeyを指定
    remoteRef:
      key: rosa_password # AWS Secrets Managerに登録したシークレット名
      property: ROSA_PASSWORD # シークレットに登録したキーを指定
