apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: es-rosa-token
spec:
  secretStoreRef:
    name: awssm
    kind: ClusterSecretStore
  target: # ExternalSecret から作成されるKubernetes Secretを指定する
    name: rosa-token
  data: # 取得する秘匿情報を指定する
  - secretKey: ROSA_TOKEN # 作成するSecretのkeyを指定
    remoteRef:
      key: rosa_token # AWS Secrets Managerに登録したシークレット名
      property: ROSA_TOKEN # シークレットに登録したキーを指定
