apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ${{ values.cluster_name }}-listener
spec:
  serviceAccountName: trigger-sa 
  triggers:
    - bindings:
        - ref: ${{ values.cluster_name }}-trigger-binding
      template:
        ref: ${{ values.cluster_name }}-pipeline-template
      interceptors:
      - ref:
          name: ${{ values.git }}
          kind: ClusterInterceptor
        params:
        - name: "secretRef"
          value:
            secretName: ${{ values.git }}-webhook-secret
            secretKey: ${{ values.git }}_webhook_secret
        - name: "eventTypes"
          value: ["push"]
