name: 'Update AWS Secrets Manager'

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup AWS Credentials 
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: "${{ secrets.AWS_ROLE_ARN }}"
        aws-region: "${{ secrets.AWS_DEFAULT_REGION }}"
        role-duration-seconds: 3600
        role-session-name: GitHubActionsCICD

    - name: Update secret in AWS Secrets Manager
      run: |
        aws secretsmanager update-secret --secret-id "${{ secrets.ROSA_CLUSTER_NAME }}_rosa_username" --secret-string "${{ secrets.ROSA_USERNAME }}"
        aws secretsmanager update-secret --secret-id "${{ secrets.ROSA_CLUSTER_NAME }}_rosa_password" --secret-string "${{ secrets.ROSA_PASSWORD }}"
