---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.cluster_name }}
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://${{ values.git_host_url }}/${{ values.git_owner_name }}/${{ values.cluster_name }}.git 
    targetRevision: main
    path: ./tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.cluster_name }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy

